# Generated by Django 3.1.6 on 2021-02-14 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='メディア種別')),
                ('slug', models.SlugField(unique=True, verbose_name='スラグ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '質問６（メディア）',
                'verbose_name_plural': '質問６（メディア）',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True, verbose_name='タイトル')),
                ('message', models.TextField(verbose_name='本文')),
            ],
            options={
                'verbose_name': 'メールマガジン',
                'verbose_name_plural': 'メールマガジン',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='同伴者')),
                ('slug', models.SlugField(unique=True, verbose_name='スラグ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '質問４（人物）',
                'verbose_name_plural': '質問４（人物）',
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='目的')),
                ('slug', models.SlugField(unique=True, verbose_name='スラグ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '質問５（目的）',
                'verbose_name_plural': '質問５（目的）',
            },
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='交通手段')),
                ('slug', models.SlugField(unique=True, verbose_name='スラグ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '質問３（交通手段）',
                'verbose_name_plural': '質問３（交通手段）',
            },
        ),
        migrations.CreateModel(
            name='Anke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='氏名')),
                ('shop', models.CharField(choices=[('ka', 'カパテリア'), ('be', '紅乙女酒造'), ('ky', '巨峰ワイン'), ('ju', '樹蘭マルシェ'), ('others', 'その他')], default='others', max_length=300, verbose_name='お店')),
                ('age', models.CharField(blank=True, choices=[('0', '20歳未満'), ('1', '20歳以上〜30歳未満'), ('2', '30歳以上〜40歳未満'), ('3', '40歳以上〜50歳未満'), ('4', '50歳以上〜60歳未満'), ('6', '60歳以上〜70歳未満'), ('7', '70歳以上')], max_length=200, null=True, verbose_name='年代')),
                ('gender', models.CharField(blank=True, choices=[('m', '男性'), ('f', '女性'), ('c', 'カスタム')], max_length=200, null=True, verbose_name='性別')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='住所')),
                ('email', models.EmailField(max_length=254, verbose_name='Eメールアドレス')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='回答日時')),
                ('status', models.CharField(choices=[('on', 'オンライン'), ('off', '紙')], default='on', max_length=200, null=True, verbose_name='回答手段')),
                ('question1', models.CharField(blank=True, choices=[('0', '初めて'), ('1', '２回目〜５回目'), ('2', '６回目〜１０回目'), ('3', '１０回以上'), ('4', '地元住民')], default='0', max_length=300, verbose_name='質問1')),
                ('question2', models.CharField(blank=True, max_length=300, null=True, verbose_name='質問2')),
                ('question7', models.CharField(blank=True, max_length=300, null=True, verbose_name='質問7')),
                ('question8', models.CharField(blank=True, choices=[('0', '1000円未満'), ('1', '1000円以上〜2000円未満'), ('2', '2000円以上〜3000円未満'), ('3', '4000円以上〜5000円未満'), ('4', '5000円以上〜10000円未満'), ('5', '10000円以上')], default='0', max_length=300, verbose_name='質問8')),
                ('question9', models.CharField(blank=True, choices=[('0', '1000円未満'), ('1', '1000円以上〜2000円未満'), ('2', '2000円以上〜3000円未満'), ('3', '4000円以上〜5000円未満'), ('4', '5000円以上〜10000円未満'), ('5', '10000円以上')], default='0', max_length=300, verbose_name='質問9')),
                ('question10', models.CharField(blank=True, max_length=300, null=True, verbose_name='質問10')),
                ('question11', models.TextField(blank=True, null=True, verbose_name='質問11')),
                ('question12', models.CharField(blank=True, max_length=300, null=True, verbose_name='質問12')),
                ('question13', models.PositiveIntegerField(blank=True, null=True, verbose_name='質問13')),
                ('question14', models.TextField(blank=True, null=True, verbose_name='質問14')),
                ('question15', models.TextField(blank=True, null=True, verbose_name='質問15')),
                ('notification', models.BooleanField(default=True, null=True, verbose_name='通知')),
                ('question3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='anke.traffic', verbose_name='質問3')),
                ('question4', models.ManyToManyField(blank=True, to='anke.Person', verbose_name='質問4')),
                ('question5', models.ManyToManyField(blank=True, to='anke.Purpose', verbose_name='質問5')),
                ('question6', models.ManyToManyField(blank=True, to='anke.Media', verbose_name='質問6')),
            ],
            options={
                'verbose_name': 'アンケート',
                'verbose_name_plural': 'アンケート',
            },
        ),
    ]
