# Generated by Django 3.1.6 on 2021-02-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anke', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anke',
            name='notification',
            field=models.BooleanField(default=False, null=True, verbose_name='通知'),
        ),
    ]
