# Generated by Django 3.1.6 on 2021-02-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anke', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anke',
            name='question3',
            field=models.CharField(choices=[('m-car', 'マイカー'), ('r-car', 'レンタカー'), ('jr', 'ＪＲ'), ('r-bus', '路線バス'), ('s-bus', '観光バス'), ('others', 'その他')], max_length=200, null=True, verbose_name='質問③'),
        ),
        migrations.AlterField(
            model_name='anke',
            name='question2',
            field=models.TextField(blank=True, null=True, verbose_name='質問②'),
        ),
    ]
