# Generated by Django 3.1.6 on 2021-02-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anke', '0003_auto_20210204_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anke',
            options={'permissions': [('kapateria', 'beniotome')], 'verbose_name': 'アンケート', 'verbose_name_plural': 'アンケート'},
        ),
        migrations.AlterField(
            model_name='anke',
            name='age',
            field=models.PositiveIntegerField(null=True, verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='anke',
            name='gender',
            field=models.CharField(choices=[('m', '男性'), ('f', '女性')], max_length=200, null=True, verbose_name='性別'),
        ),
    ]
