# Generated by Django 3.1.6 on 2021-02-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anke', '0003_auto_20210215_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-created'], 'verbose_name': 'メールマガジン', 'verbose_name_plural': 'メールマガジン'},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='回答日時'),
        ),
    ]
