# Generated by Django 3.1.6 on 2021-02-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anke', '0004_auto_20210215_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時'),
        ),
    ]
