# Generated by Django 3.1.6 on 2021-02-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anke', '0005_auto_20210204_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='交通手段')),
                ('slug', models.SlugField(unique=True, verbose_name='スラグ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '交通',
                'verbose_name_plural': '交通',
            },
        ),
        migrations.RemoveField(
            model_name='anke',
            name='question3',
        ),
        migrations.AddField(
            model_name='anke',
            name='question3',
            field=models.ManyToManyField(blank=True, max_length=200, null=True, to='anke.Traffic', verbose_name='質問③'),
        ),
    ]
