# Generated by Django 3.1.6 on 2021-02-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anke', '0006_auto_20210205_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anke',
            name='question3',
            field=models.ManyToManyField(blank=True, max_length=200, to='anke.Traffic', verbose_name='質問③'),
        ),
    ]
