# Generated by Django 3.1.6 on 2021-02-06 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anke', '0007_auto_20210205_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='メディア種別')),
                ('slug', models.SlugField(unique=True, verbose_name='スラグ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'メディア',
                'verbose_name_plural': 'メディア',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='同伴者')),
                ('slug', models.SlugField(unique=True, verbose_name='スラグ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '人物',
                'verbose_name_plural': '人物',
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='目的')),
                ('slug', models.SlugField(unique=True, verbose_name='スラグ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '目的',
                'verbose_name_plural': '目的',
            },
        ),
        migrations.AlterField(
            model_name='anke',
            name='question1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='質問①'),
        ),
        migrations.RemoveField(
            model_name='anke',
            name='question3',
        ),
        migrations.AddField(
            model_name='anke',
            name='question3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='anke.traffic', verbose_name='質問③'),
        ),
        migrations.AddField(
            model_name='anke',
            name='question4',
            field=models.ManyToManyField(blank=True, to='anke.Person', verbose_name='質問④'),
        ),
        migrations.AddField(
            model_name='anke',
            name='question5',
            field=models.ManyToManyField(blank=True, to='anke.Purpose', verbose_name='質問⑤'),
        ),
        migrations.AddField(
            model_name='anke',
            name='question6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='anke.media', verbose_name='質問⑥'),
        ),
    ]
