# Generated by Django 3.1.6 on 2021-02-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anke', '0008_auto_20210206_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': '質問６（メディア）', 'verbose_name_plural': '質問６（メディア）'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '質問４（人物）', 'verbose_name_plural': '質問４（人物）'},
        ),
        migrations.AlterModelOptions(
            name='purpose',
            options={'verbose_name': '質問５（目的）', 'verbose_name_plural': '質問５（目的）'},
        ),
        migrations.AlterModelOptions(
            name='traffic',
            options={'verbose_name': '質問３（交通手段）', 'verbose_name_plural': '質問３（交通手段）'},
        ),
        migrations.AlterField(
            model_name='anke',
            name='question2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='質問②'),
        ),
    ]
