# Generated by Django 3.1.6 on 2021-02-06 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anke', '0009_auto_20210206_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='anke',
            name='question10',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='質問10'),
        ),
        migrations.AddField(
            model_name='anke',
            name='question11',
            field=models.TextField(blank=True, null=True, verbose_name='質問11'),
        ),
        migrations.AddField(
            model_name='anke',
            name='question12',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='質問12'),
        ),
        migrations.AddField(
            model_name='anke',
            name='question13',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='質問13'),
        ),
        migrations.AddField(
            model_name='anke',
            name='question14',
            field=models.TextField(blank=True, null=True, verbose_name='質問14'),
        ),
        migrations.AddField(
            model_name='anke',
            name='question15',
            field=models.TextField(blank=True, null=True, verbose_name='質問15'),
        ),
        migrations.AddField(
            model_name='anke',
            name='question7',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='質問7'),
        ),
        migrations.AddField(
            model_name='anke',
            name='question8',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='質問8'),
        ),
        migrations.AddField(
            model_name='anke',
            name='question9',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='質問9'),
        ),
        migrations.AlterField(
            model_name='anke',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='anke',
            name='question1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='質問1'),
        ),
        migrations.AlterField(
            model_name='anke',
            name='question2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='質問2'),
        ),
        migrations.AlterField(
            model_name='anke',
            name='question3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='anke.traffic', verbose_name='質問3'),
        ),
        migrations.AlterField(
            model_name='anke',
            name='question4',
            field=models.ManyToManyField(blank=True, to='anke.Person', verbose_name='質問4'),
        ),
        migrations.AlterField(
            model_name='anke',
            name='question5',
            field=models.ManyToManyField(blank=True, to='anke.Purpose', verbose_name='質問5'),
        ),
        migrations.AlterField(
            model_name='anke',
            name='question6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='anke.media', verbose_name='質問6'),
        ),
        migrations.AlterField(
            model_name='anke',
            name='gender',
            field=models.CharField(choices=[('m', '男性'), ('f', '女性')], default='f', max_length=200, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='anke',
            name='shop',
            field=models.CharField(choices=[('ka', 'カパテリア'), ('be', '紅乙女酒造'), ('ky', '巨峰ワイン'), ('ju', '樹蘭マルシェ'), ('others', 'その他')], max_length=300, null=True, verbose_name='お店'),
        ),
    ]
