# Generated by Django 3.1.6 on 2021-02-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anke', '0012_auto_20210206_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anke',
            name='question6',
        ),
        migrations.AddField(
            model_name='anke',
            name='question6',
            field=models.ManyToManyField(blank=True, to='anke.Media', verbose_name='質問6'),
        ),
    ]
