# Generated by Django 3.1.6 on 2021-02-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anke', '0013_auto_20210206_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anke',
            name='question1',
            field=models.CharField(blank=True, choices=[('0', '初めて'), ('1', '２回目〜５回目'), ('2', '６回目〜１０回目'), ('3', '１０回以上'), ('4', '地元住民')], default='0', max_length=300, verbose_name='質問1'),
        ),
        migrations.AlterField(
            model_name='anke',
            name='question8',
            field=models.CharField(blank=True, choices=[('0', '1000円未満'), ('1', '1000円以上〜2000円未満'), ('2', '2000円以上〜3000円未満'), ('3', '4000円以上〜5000円未満'), ('4', '5000円以上〜10000円未満'), ('5', '10000円以上')], default='0', max_length=300, verbose_name='質問8'),
        ),
        migrations.AlterField(
            model_name='anke',
            name='question9',
            field=models.CharField(blank=True, choices=[('0', '1000円未満'), ('1', '1000円以上〜2000円未満'), ('2', '2000円以上〜3000円未満'), ('3', '4000円以上〜5000円未満'), ('4', '5000円以上〜10000円未満'), ('5', '10000円以上')], default='0', max_length=300, verbose_name='質問9'),
        ),
    ]
