# Generated by Django 3.1.6 on 2021-02-09 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anke', '0014_auto_20210206_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anke',
            name='user',
        ),
    ]
