# Generated by Django 3.1.6 on 2021-02-09 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anke', '0015_remove_anke_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anke',
            options={'verbose_name': 'アンケート', 'verbose_name_plural': 'アンケート'},
        ),
    ]
