# Generated by Django 3.1.6 on 2021-02-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anke', '0016_auto_20210209_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anke',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', '男性'), ('f', '女性'), ('c', 'カスタム')], max_length=200, null=True, verbose_name='性別'),
        ),
    ]
