# Generated by Django 3.1.6 on 2021-02-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anke', '0016_auto_20210209_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='anke',
            name='notification',
            field=models.BooleanField(default=True, null=True, verbose_name='通知'),
        ),
    ]
