# Generated by Django 3.1.6 on 2021-02-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anke', '0017_anke_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True, verbose_name='タイトル')),
                ('message', models.TextField(verbose_name='本文')),
            ],
            options={
                'verbose_name': 'メールマガジン',
                'verbose_name_plural': 'メールマガジン',
            },
        ),
    ]
